spring.application.name=SmartWareHouse
jwt.secret=SuperSecretKeyJwt123456789SuperSecretKey
jwt.expiration=86400000
spring.datasource.url=jdbc:mysql://db:3306/smartwarehousenewbd?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password="#AlanBaker34"

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
